# Generated by Django 4.2.7 on 2024-10-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_trainer_achievements_trainer_qualification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direction',
            options={'ordering': ['name'], 'verbose_name': 'Направление', 'verbose_name_plural': 'Направления'},
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'ordering': ['name'], 'verbose_name': 'Тренер', 'verbose_name_plural': 'Тренеры'},
        ),
    ]
