# Generated by Django 4.2.7 on 2024-11-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0003_alter_direction_options_alter_trainer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='direction',
            field=models.ManyToManyField(related_name='trainer_directions', to='sport.direction'),
        ),
    ]
