# Generated by Django 4.2.7 on 2024-10-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0008_alter_event_description_alter_event_max_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
    ]
