# Generated by Django 4.2.7 on 2024-10-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_users', '0001_initial'),
        ('calendarapp', '0009_alter_event_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='events', to='tg_users.telegramuser'),
        ),
    ]
