# Generated by Django 4.2.7 on 2024-12-05 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('tg_id', models.CharField(max_length=100, unique=True, verbose_name='Telegram ID')),
                ('tg_full_name', models.CharField(max_length=255, verbose_name='Telegram Full Name')),
                ('tg_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram Username')),
                ('is_subscribed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Телеграм-пользователь',
                'verbose_name_plural': 'Телеграм-пользователи',
            },
        ),
    ]
